apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-github-tekton-11april-development
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/nodejs-github-tekton-11april/overlays/development
    repoURL: https://github.com/RHTAP-RHDH/nodejs-github-tekton-11april-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-development
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
