apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nodejs-github-tekton-11april 
  janus-idp.io/tekton: nodejs-github-tekton-11april
  backstage.io/kubernetes-id: nodejs-github-tekton-11april
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodejs-github-tekton-11april
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml