apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nodejs-github-tekton-11april-gitops
  description: This is GitOps manifest for nodejs-github-tekton-11april   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=nodejs-github-tekton-11april
    backstage.io/kubernetes-id: nodejs-github-tekton-11april 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: nodejs-github-tekton-11april
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nodejs-github-tekton-11april
