apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nodejs-github-tekton-11april
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-github-tekton-11april 
  name: nodejs-github-tekton-11april
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nodejs-github-tekton-11april 
